version: "3.4"

services:
  web:
    image: httpd:latest
    volumes:
      - ./web/bin:/usr/local/apache2/htdocs 
    ports:
      - 80:80
      
  db:
    image: gvenzl/oracle-free:latest
    environment:
      - ORACLE_PASSWORD=pass
      - APP_USER=maria
      - APP_USER_PASSWORD=pass
    ports:
      - 1521

  api:
    build: api
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:1521
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "81:5000"
